inventoryapp-elasticsearch:
  container_name: inventoryapp-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/InventoryApp/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
inventoryapp-postgresql:
  container_name: inventoryapp-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/InventoryApp/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=InventoryApp
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
